Adds SciQLop and PyCDFpp projects and update a bit Speasy entry
heliophysicsPy/heliophysicsPy.github.io pull request #297
Opened 2023-11-02 11:47 UTC by jeandet

SciQLop has quite some red badges but that would be nice if we can advertise it a bit.

2023-11-16 19:10 UTC, sapols commented
Hi, sorry for the super slow response. I've got a backlog of other tasks before I can start this review, and with holidays/conferences it might be a while.

2024-01-08 17:46 UTC, sapols commented
Sorry again, I've had a slow start to the year. I'll get to this review in the next week or so. Just wanted to let you know it's still bubbling up my to-do list.

2024-01-09 14:51 UTC, jeandet commented
> Sorry again, I've had a slow start to the year. I'll get to this review in the next week or so. Just wanted to let you know it's still bubbling up my to-do list.

No problem 😁.

2024-01-18 18:15 UTC, sapols requested changes
I agree with your self-evaluations. We just can't merge this until the keywords are fixed. Please let me know if you'd like any assistance.

2024-01-18 18:15 UTC, sapols commented on _data/projects.yml
> +  keywords: ["heliophysics", "space physics", "magnetospheric physics", "CDF", "data"]
Please redo these keywords as they must come from PyHC's [taxonomy](https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/main/_data/taxonomy.yml). If you feel the taxonomy is missing something, you may add to it in this PR.

2024-01-18 18:15 UTC, sapols commented on _data/projects.yml
> +  keywords: ["heliophysics", "space physics", "magnetospheric physics", "Machine-learning", "data"]
Same comment for these keywords.

2024-01-18 18:17 UTC, sapols commented
Finally got around to reviewing this. I notice there's a merge conflict now though, and that's my bad. I merged another PR before yours that added Hermes-Core to this `projects.yml`. I'll see if I can resolve it myself.

2024-01-18 18:21 UTC, sapols commented
Merge conflict resolved. I put the HERMES-Core entry above your new ones.

2024-01-19 09:48 UTC, jeandet commented
@sapols I've rebased the commit with the requested modifications, sorry I've missed the guidelines for keywords 😅.

2024-01-19 12:46 UTC, sapols approved these changes
Awesome! No worries, this PR looks good now. Welcome SciQLop and PyCDFpp to PyHC.

2024-01-19 12:48 UTC, merged