Organize Meetings page into subpages
heliophysicsPy/heliophysicsPy.github.io pull request #310
Opened 2024-01-18 01:06 UTC by sapols

This PR cleans up our [Meetings](https://pyhc.org/meetings) page by grouping things into subpages. 

Now, everything that used to be below the calendar has been moved into one of 3 subpages:
- **Community Meetings**
- **Conference Sessions**
- **Summer Schools**

These subpages are now listed in-between our telecon info and the calendar.

## Implementation notes:

- The subpage links are H3s like the other two headers on the page.
- I waffled between single- or double-spacing the subpage links. It's single-spaced right now. Double spacing visually separates the links more, but it looked like a whole lot of whitespace. _Do you have any preference either way?_
- The refactor involved shuffling around file locations:
     - Now, rather than dumping every .md file into the `meetings/` folder, they go in one of 3 subfolders (`community_meetings/`, `conference_sessions/`, `summer_schools/`).
     - I had to fix a bunch of relative links after I moved those files.

2024-01-19 23:59 UTC, jibarnum requested changes
<img width="1442" alt="Screenshot 2024-01-19 at 4 50 12 PM" src="https://github.com/heliophysicsPy/heliophysicsPy.github.io/assets/23218684/1c9b41a9-d132-43d9-8bef-4e707c19b6c4">

Overall, loving the way it's been reorganized. This is so much cleaner and easier to navigate. Just one small request: can we make a black font header like there is for Telecons and Calendar, saying something to the effect of "PyHC Relevant Meetings" (feel free to wordsmith however you want)? I think that'd make the page flow even better.

2024-01-20 00:17 UTC, sapols commented
@jibarnum is this better? With `Events`? 

I'd specifically wrestled with this idea when I was making this PR, but initially decided against it because any header I could think of was either redundant or inaccurate. (1) It's already the "Meetings" page so no point in having a second header that says "meetings", (2) Telecons are also "PyHC relevant meetings" so we can't use that, (3) "Events" is the best I can come up with, but "Community Meetings" are really more "meeting" than "event."

<img width="1536" alt="Screen Shot 2024-01-19 at 5 11 37 PM" src="https://github.com/heliophysicsPy/heliophysicsPy.github.io/assets/14846863/fbb9f6b6-4fc0-4ee5-adeb-7a0ce835172f">

2024-01-20 00:20 UTC, jibarnum commented
> @jibarnum is this better? With `Events`?
> 
> I'd specifically wrestled with this idea when I was making this PR, but initially decided against it because any header I could think of was either redundant or inaccurate. (1) It's already the "Meetings" page so no point in having a second header that says "meetings", (2) Telecons are also "PyHC relevant meetings" so we can't use that, (3) "Events" is the best I can come up with, but "Community Meetings" are really more "meeting" than "event."
> 
> <img alt="Screen Shot 2024-01-19 at 5 11 37 PM" width="1536" src="https://private-user-images.githubusercontent.com/14846863/298237993-fbb9f6b6-4fc0-4ee5-adeb-7a0ce835172f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTAyNDcsIm5iZiI6MTcwNTcwOTk0NywicGF0aCI6Ii8xNDg0Njg2My8yOTgyMzc5OTMtZmJiOWY2YjYtNGZjMC00ZWU1LWFkZWItN2EwY2U4MzUxNzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDAwMTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NjI5NWZjYmQxZjE2ZDkwNDgyNzllZjU0ZWM3YTM5ZjE2N2RjNzExYjFmNTQ4ODE3MmQxMTIwMDM4YzkxOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qhHR_c2lDbPrmIRjRHcTCZt2C-IMx3lQdcqWxCEIyoY">

Totally, I can see how adding Meetings again in there is redundant. I just wanted _something_ there to break up the flow. Even though meetings are more meetings than they are events, I still like the title "Events".

2024-01-20 00:27 UTC, jibarnum approved these changes

2024-01-20 00:28 UTC, merged